### ISSUE TITLE
文档描述有误

### ISSUE THREAD

**Issue by slp1608** [wangdoc/javascript-tutorial#104]
a元素这一章节里的1.2 accessKey 属性，html里a标签的id是"test"，下面getElementById('a')。
![WeChat Screenshot_20190311133619](https://user-images.githubusercontent.com/22806335/54102285-c0655300-4402-11e9-8059-bd3bb4411538.png)

**Comment by slp1608** [comment]
a元素，

**Comment by ruanyf** [comment]
谢谢反馈，已经改正。
