### ISSUE TITLE
文档描述语义可能有不全

### ISSUE THREAD

**Issue by LoveNormalDay** [wangdoc/javascript-tutorial#109]
您好
标准库-属性描述对象-6.4configurable

![image](https://user-images.githubusercontent.com/16485250/54414048-c5900e00-4732-11e9-9e0b-6ac00d994343.png)
您文章里已经说了，使用define定义属性的时候，writable，configurable，enumerable这三个默认是false，而您图上的第一个例子也说了writable或者configurable任意一个为trur就可以修改value，第二个例子里不能修改的原因，不仅仅是直接通过赋值属性失败，而是默认的writable为false，而且configurable也主动设置了false，所以这个属性才不能通过直接赋值修改

**Comment by ruanyf** [comment]
谢谢指出，这里改成`writable`了。
