### ISSUE TITLE
文档描述可能不清晰

### ISSUE THREAD

**Issue by LoveNormalDay** [wangdoc/javascript-tutorial#110]
您好
DOM-Node节点-2.1Node.prototype.appendChild()
![image](https://user-images.githubusercontent.com/16485250/54667001-45005180-4b26-11e9-82d4-556c5e1e35a0.png)

返回b的原因是appendChild会返回添加的节点.我感觉标注的这句话这下面举的例子不是一个意思。

标注的意思是如果我直接拿已有元素添加到其他元素会修改原有元素的位置，但是举例其实是想说appendChild会返回添加的节点

**Comment by ruanyf** [comment]
谢谢指出，这个例子确实不好，我换掉它。
