### ISSUE TITLE
文档代码存在多余

### ISSUE THREAD

**Issue by LoveNormalDay** [wangdoc/javascript-tutorial#112]
您好：
浏览器模型-XMLHttpRequest 对象-3.6XMLHttpRequest.getAllResponseHeaders()
![image](https://user-images.githubusercontent.com/16485250/54823263-48d8d300-4ce2-11e9-94fe-4b3f02f6294f.png)
代码parts.join(': ');在这里的意思和parts一样，只有数组只有一个参数的时候join添加的分隔符不起作用。

**Comment by ruanyf** [comment]
这里没有问题啊，用来恢复 HTTP 头元素的值。如果数组只有一个元素，就不加冒号。
