### ISSUE TITLE
关于JavaScript教程 数据类型-函数5.1闭包中的一个小问题

### ISSUE THREAD

**Issue by junglehunter96** [wangdoc/javascript-tutorial#114]
![image](https://user-images.githubusercontent.com/48642399/54919619-38239980-4f3c-11e9-8638-7538eda8a08d.png)
如图 此处是否是编辑文字的时候少打了 一个return
`function setAge(n) {
    _age = n;`

**Comment by ruanyf** [comment]
`setAge()`函数不需要 return，也可以生效啊
