### ISSUE TITLE
“JavaScript教程 / DOM / Node接口”章节首尾部分的下翻页导航文字存在错误。

### ISSUE THREAD

**Issue by ahhfjjj** [wangdoc/javascript-tutorial#115]
您好，在 JavaScript教程 / DOM / Node接口 章节首尾部分，下翻页的文字描述显示“lodeList接口...”，是否应该为“Nodelist接口...”?
<img width="866" alt="Node接口章节截图" src="https://user-images.githubusercontent.com/10154594/55276061-afd13a00-5329-11e9-909c-4d3337180daa.png">

**Comment by ruanyf** [comment]
这里的 CSS 有长度限制，所以没有全部显示出来，并不是文字错误。我再想想怎么处理。
