### ISSUE TITLE
有一个写错的单词～

### ISSUE THREAD

**Issue by yaogengzhu** [wangdoc/javascript-tutorial#123]
function showChar(e) {
  console.log('ALT: ' + e.altKey);
  console.log('CTRL: ' + e.ctrlKey);
  console.log('Meta: ' + e.metaKey);
  console.log('Meta: ' + e.shiftKey);
}

document.body.addEventListener('keydown', showChar, false);
// .有一个问题     第四个执行的console.log（'shift' + e.shiftKey);

**Comment by ruanyf** [comment]
谢谢指出，已经改正。
