### ISSUE TITLE
属性描述对象章节几个默认值有错误

### ISSUE THREAD

**Issue by coddylau** [wangdoc/javascript-tutorial#145]
阮老师，我在[属性描述对象](https://wangdoc.com/javascript/stdlib/attributes.html)章节
发现Object.defineProperty的几个属性的默认值有误，
这些属性
  writable: false,
  enumerable: false,
  configurable: false
默认值都是false，你写了true，附上[MDN链接](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty)

**Comment by ruanyf** [comment]
https://wangdoc.com/javascript/stdlib/attributes.html#objectdefineproperty%EF%BC%8Cobjectdefineproperties

**Comment by coddylau** [comment]
不好意思没有描述清楚
stdlib/attributes.md 文件下26到36行之间，你有写这些属性的默认为true

**Comment by coddylau** [comment]
> https://wangdoc.com/javascript/stdlib/attributes.html#objectdefineproperty%EF%BC%8Cobjectdefineproperties

不好意思没有描述清楚
stdlib/attributes.md 文件下26到36行之间，你有写这些属性的默认为true

**Comment by ruanyf** [comment]
属性的默认值与 defineProperty() 产生的属性默认值是不一样的。

**Comment by coddylau** [comment]
嗯，后来再次测试了一下，直接设置一个属性，默认值是true，通过defineProperty定义的属性默认值是false，谢谢阮老师
