### ISSUE TITLE
函数作为另一个函数参数问题

### ISSUE THREAD

**Issue by Iamxiaozhu** [wangdoc/javascript-tutorial#149]
> 如果函数参数是复合类型的值（数组、对象、其他函数），传递方式是传址传递（pass by reference）。也就是说，传入函数的原始值的地址，因此在函数内部修改参数，将会影响到原始值。

但是函数作为参数，并没有影响原始值
`function p(){alert(1)};

function f(p) {
  p = function(){alert(2)};
}
f(p);

p  //ƒ p(){alert(1)}`

**Comment by ruanyf** [comment]
`p`是指向函数的指针啊。
