### ISSUE TITLE
为什么 Array 的 forEach 方法的回调函数中的 this 默认指向 window ？

### ISSUE THREAD

**Issue by wotent** [wangdoc/javascript-tutorial#150]
关于数组的 forEach 中的 this，有点不理解。

[4.2 避免数组处理方法中的 this](https://wangdoc.com/javascript/oop/this.html#%E9%81%BF%E5%85%8D%E6%95%B0%E7%BB%84%E5%A4%84%E7%90%86%E6%96%B9%E6%B3%95%E4%B8%AD%E7%9A%84-this)  中提到：
> ```javascript
> var o = {
>   v: 'hello',
>   p: [ 'a1', 'a2' ],
>   f: function f() {
>     this.p.forEach(function (item) {
>       console.log(this.v + ' ' + item);
>     });
>   }
> }
> 
> o.f()
> // undefined a1
> // undefined a2
> ```
> `foreach`方法的回调函数中的`this`，其实是指向`window`对象。

 [22.1.3.12Array.prototype.forEach ( callbackfn [ , thisArg ] )](http://www.ecma-international.org/ecma-262/10.0/index.html#sec-array.prototype.foreach) 指出：

> If a thisArg parameter is provided, it will be used as the this value for each invocation of callbackfn. If it is not provided, undefined is used instead.

把 forEach 改为：
```javascript
    this.p.forEach(function (item) {
      console.log(this.v + ' ' + item);
    }, undefined);
```
后，this 不是 undefined，而是指向 window，这是为什么？

**Comment by ruanyf** [comment]
看看 V8 源码。

**Comment by 1316346949** [comment]
this.p.forEach(function (item) {
      console.log(this.v + ' ' + item);
    }, undefined);
貌似还是指向undefined

**Comment by 1316346949** [comment]
@wotent

**Comment by wotent** [comment]
`this.v` 改为 `this`

``` JavaScript
    this.p.forEach(function (item) {
      console.log(this + ' ' + item);
    }, undefined);
```

后，输出如下：

```
[object Window] a1
[object Window] a2
```

会发现，传入 `undefined`，但 `forEach` 中的 `this` 实际指向 `window` 对象。

[5.1 Function.prototype.call()](https://wangdoc.com/javascript/oop/this.html#functionprototypecall) 中提到：

> `call`方法的参数，应该是一个对象。如果参数为空、`null`和`undefined`，则默认传入全局对象。

`Array.prototype.forEach ( callbackfn [ , thisArg ] )`中一定调用了`Function.prototype.call ( thisArg, ...args )`方法，`thisArg`传入`undefined`，则被转换为全局对象`window`。

<hr/>

但是 [19.2.3.3 Function.prototype.call ( thisArg, ...args )](http://www.ecma-international.org/ecma-262/10.0/index.html#sec-function.prototype.call) 中提到：

> The thisArg value is passed without modification as the this value. This is a change from Edition 3, where an undefined or null thisArg is replaced with the global object and ToObject is applied to all other values and that result is passed as the this value. Even though the thisArg is passed without modification, non-strict functions still perform these transformations upon entry to the function.

所以，在“non-strict”下，`Array`的`forEach`方法的回调函数中的`this`默认指向`window`；而在"use strict"下，`Array`的`forEach`方法的回调函数中的`this`默认为 `undefined`。

源码实在看不懂，只能这么理解了。

@ruanyf @1316346949
