### ISSUE TITLE
有一个地方好像写错了

### ISSUE THREAD

**Issue by 1316346949** [wangdoc/javascript-tutorial#153]
![image](https://user-images.githubusercontent.com/24400797/66741604-79fc3900-eea8-11e9-917d-cebc6acfe6b3.png)

**Comment by 1316346949** [comment]
我试了下端口不通获取js脚本可以获取document对象，不知道是否我的验证方法不正确

**Comment by ruanyf** [comment]
它的意思是同源才能获取 DOM。

**Comment by 1316346949** [comment]
> 它的意思是同源才能获取 DOM。

我试了下，在本地起了两个http服务，不同端口，一个端口返回html引用另一个端口返回的js文件，可以获取dom，并且修改样式
