### ISSUE TITLE
大佬你好，貌似ParentNode这篇有问题？

### ISSUE THREAD

**Issue by 1316346949** [wangdoc/javascript-tutorial#157]
![image](https://user-images.githubusercontent.com/24400797/69411303-a6c52b00-0d47-11ea-8447-4e88126c20c9.png)
我试了下没有找到获取ParentNode类的方法，并且无法验证元素节点的父节点继承ParentNode

**Comment by 1316346949** [comment]
例如document.body.parentElement或者document.body.parentNode的原型链找不到ParentNode接口，试了一些方法获取的不管是NodeList，还是HTMLCollection，还是普通element元素都无法在他们原型链上找到ParentNode

**Comment by 1316346949** [comment]
ChildNode 这个接口貌似也是没有的？

**Comment by ruanyf** [comment]
我改一下，ParentNode 和 ChildNode 都是混入的（Mixin），不是继承。

**Comment by 1316346949** [comment]
> ParentNode
