### ISSUE TITLE
CSS 操作 > 关于 StyleSheet 接口和 CSSStyleSheet 接口

### ISSUE THREAD

**Issue by itellboy** [wangdoc/javascript-tutorial#16]
阮老师，您好，从您的许多开源文档中我学到的很多的基础知识，非常感谢，我也希望在从中获取的同时也贡献自己的一部分力量。
在 CSS 操作这一篇中关于 StyleSheet 接口这一部分存在一些小问题，我在 MDN 上面查到 StyleSheet 接口是 CSSStyleSheet 接口的父接口，其中 disabled, href, media, ownerNode, parentStyleSheet, title, type 属于 StyleSheet 实例的属性，而 cssRules, ownerRule 属于 CSSStypeSheet 实例的属性。目前在文档里面未体现两个接口之间的关系

**Comment by ruanyf** [comment]
这里不区分了 StyleSheet 和 CSSStypeSheet 了。因为对于实际开发的意义不大，反而徒增了复杂度。着一章本来就很复杂了。
