### ISSUE TITLE
科学计数法的有效位范围不一致

### ISSUE THREAD

**Issue by RichardDegeneres** [wangdoc/javascript-tutorial#162]
![image](https://user-images.githubusercontent.com/37562985/75544379-c8c4fc80-5a5e-11ea-84a2-6f2300d5765d.png)

**Comment by RichardDegeneres** [comment]
![image](https://user-images.githubusercontent.com/37562985/75544785-a089cd80-5a5f-11ea-8828-da38dd8b4d2d.png)

**Comment by ruanyf** [comment]
谢谢指出，已经改正。
