### ISSUE TITLE
promise 状态中 resolved 名词解释与使用不一致

### ISSUE THREAD

**Issue by RichardDegeneres** [wangdoc/javascript-tutorial#166]
![image](https://user-images.githubusercontent.com/37562985/76843493-d5c35780-6876-11ea-87a1-17fae42da35c.png)

**Comment by RichardDegeneres** [comment]
对于 resolved 概念 的理解有些模糊，请教阮老师

**Comment by ruanyf** [comment]
参考 ES6 的标准。https://tc39.es/ecma262/#sec-promise-objects

> A promise is said to be settled if it is not pending, i.e. if it is either fulfilled or rejected.
> 
> A promise is resolved if it is settled or if it has been “locked in” to match the state of another promise. Attempting to resolve or reject a resolved promise has no effect. A promise is unresolved if it is not resolved. An unresolved promise is always in the pending state. A resolved promise may be pending, fulfilled or rejected.
