### ISSUE TITLE
关于instanceof运算符

### ISSUE THREAD

**Issue by chenzhiwei0109** [wangdoc/javascript-tutorial#172]
https://wangdoc.com/javascript/stdlib/object.html  
关键词搜索instanceof;
**instanceof`运算符用来验证，一个对象是否为指定的构造函数的实例。**
这句话感觉不太准确，instanceof不一定是指定构造函数实例啊。'

**Comment by ruanyf** [comment]
参考 https://wangdoc.com/javascript/oop/prototype.html#instanceof-%E8%BF%90%E7%AE%97%E7%AC%A6

**Comment by chenzhiwei0109** [comment]
谢谢老师，之前看MDN中文文档没有提及这一点，[] 既是Object的实例又是Array的实例。只是说检测构造函数的prototype属性出现在[]的原型链上。英文的原意的确是判断是否是构造函数的实例！
