### ISSUE TITLE
运算符一章中错别字

### ISSUE THREAD

**Issue by doxingg** [wangdoc/javascript-tutorial#173]
运算符-》布尔运算符[且运算符](https://wangdoc.com/javascript/operators/boolean.html#%E4%B8%94%E8%BF%90%E7%AE%97%E7%AC%A6%EF%BC%88%EF%BC%89)
有个字应该错了
![image](https://user-images.githubusercontent.com/38033238/81514263-a86bc500-9360-11ea-8f0b-b131aa880fd3.png)
这个`所有`应该是`所以`

**Comment by ruanyf** [comment]
谢谢指出，已经改正。
