### ISSUE TITLE
存取器（accessor）两种写法不等价

### ISSUE THREAD

**Issue by ixialuo** [wangdoc/javascript-tutorial#175]
文档路径：[标准库 -> 属性描述对象 -> 7.存储器](https://wangdoc.com/javascript/stdlib/attributes.html)
原文：上面的写法与定义属性描述对象是等价的，而且使用更广泛。（备注：上面的写法指下文写法②；定义属性对象指下文写法①）

写法①：
```
var obj = Object.defineProperty({}, 'p', {
  get: function () {
    return 'getter';
  },
  set: function (value) {
    console.log('setter: ' + value);
  }
});
```
写法②：
```
var obj = {
  get p() {
    return 'getter';
  },
  set p(value) {
    console.log('setter: ' + value);
  }
};
```

不等价之处：
写法①：Object.defineProperty() 参数里面的属性描述对象，configurable、enumerable 属性默认值都为 false，从而导致属性 p 是不可遍历的;
写法②：这种写法属性描述对象，configurable、enumerable 属性为 true，属性 p 是可遍历的。

**Comment by ruanyf** [comment]
谢谢指出，已经改正。
