### ISSUE TITLE
是否可以更新一些常用方法

### ISSUE THREAD

**Issue by WaterMr** [wangdoc/javascript-tutorial#177]
Object.values()
这个常用的方法在标准库->Object对象中没有说明

**Comment by ruanyf** [comment]
在 ES6 的教程里面。

https://wangdoc.com/es6/array.html#%E6%95%B0%E7%BB%84%E5%AE%9E%E4%BE%8B%E7%9A%84-entries%EF%BC%8Ckeys-%E5%92%8C-values
