### ISSUE TITLE
关于订阅/发布模式和观察者模式

### ISSUE THREAD

**Issue by HuilingDu** [wangdoc/javascript-tutorial#178]
老师好！我看到“异步操作的模式”中讲到：”发布/订阅模式”（publish-subscribe pattern），又称“观察者模式”（observer pattern）。
但是在网上很多是把这两种模式区分开的，不知道老师有没有写过相关的专题讲解，想深入了解一下。

**Comment by ruanyf** [comment]
参考设计模式的书籍，这个不是很重要。
