### ISSUE TITLE
比较运算符存在描述不准确的地方

### ISSUE THREAD

**Issue by laixiaotao** [wangdoc/javascript-tutorial#185]
文档路径：[运算符 > 比较运算符 > 非相等运算符：非字符串的比较](https://wangdoc.com/javascript/operators/comparison.html#%E9%9D%9E%E7%9B%B8%E7%AD%89%E8%BF%90%E7%AE%97%E7%AC%A6%EF%BC%9A%E5%AD%97%E7%AC%A6%E4%B8%B2%E7%9A%84%E6%AF%94%E8%BE%83)
原文：上面代码中，字符串和布尔值都会先转成数值，再进行比较。这里需要注意与NaN的比较。任何值（包括NaN本身）与NaN比较，返回的都是false。
建议：虽然知道阮老师想要表达使用非相等比较运算符与 NaN 的比较均为 false，但是感觉应当是表述为除了 != 与 !== 以外的比较，不然存在一定误解。

**Comment by ruanyf** [comment]
谢谢提醒，已经修改了。
