### ISSUE TITLE
相等运算符规则出现描述错误和与实际情况不相等的情况

### ISSUE THREAD

**Issue by laixiaotao** [wangdoc/javascript-tutorial#186]
文档路径：[运算符 > 比较运算符 > 相等运算符](https://wangdoc.com/javascript/operators/comparison.html#%E7%9B%B8%E7%AD%89%E8%BF%90%E7%AE%97%E7%AC%A6)

#### 问题
在第二小段（2）对象与原始类型值比较示例部分，
```javascript
// 对象与字符串比较时，对象转为字符串
[1] == '1' // true
// 等同于 String([1]) == '1'
[1, 2] == '1,2' // true
// 等同于 String([1, 2]) == '1,2'
```
以及接下来的描述
>上面代码中，数组[1]与数值进行比较，会先转成数值，再进行比较；与字符串进行比较，会先转成字符串，再进行比较；与布尔值进行比较，对象和布尔值都会先转成数值，再进行比较

#### 测试
经测试，对象与字符串比较时，并非简单地类似执行了 String() 方法，而是依旧先调用 valueOf 方法，toString 方法，而且也并非对象返回的原始值直接转换为字符串再和字符串比较；而是转成了数值再比较
```javascript
const obj = {
    valueOf: () => {
        console.log("执行了valueOf");
        return true
    },
    toString: () => {
        console.log("执行了toString");
        return "true"
    }
}

console.log("true" == obj); // 执行了valueOf,false
console.log(     1 == obj); // 执行了valueOf,true
```

**Comment by ruanyf** [comment]
谢谢指出，已经更正。
