### ISSUE TITLE
闭包一章中函数外部应当是可以读取内部变量的

### ISSUE THREAD

**Issue by jacty** [wangdoc/javascript-tutorial#188]
原文：https://wangdoc.com/javascript/types/function.html#%E9%97%AD%E5%8C%85
5.1 闭包中，第4 段落开头：
“但是，函数外部无法读取函数内部声明的变量”。
我觉得这里似乎有点歧义。我的观点是内部声明的变量 return 出来后还是可以被外部环境使用的。 所以，这句话是不是该改成：“大多数情况下，函数外部是无法读取函数内部声明的变量的。”？
倘若我的观点无误的话，似乎这个例子下面的那一句也需要做出相应修改。
“上面代码中，函数f1 内部声明的变量n， 函数外是无法【直接】读取的。”

或者从【是否可以读取内部声明的变量】的角度，改成【是否可以访问内部环境的角度】来解释？

**Comment by ruanyf** [comment]
改成“正常情况下”吧。

那个例子确实是无法读取的，就不用改。
