### ISSUE TITLE
错别字

### ISSUE THREAD

**Issue by eusing** [wangdoc/javascript-tutorial#19]
https://wangdoc.com/javascript/features/conversion.html
强制转换主要指使用Number、String和Boolean三个函数，手动将各种类型的值，分布转换成数字、字符串或者布尔值。

强制转换主要指使用Number、String和Boolean三个函数，手动将各种类型的值，【分布】转换成数字、字符串或者布尔值。

分布 应该是错别字吧

**Comment by ruanyf** [comment]
谢谢指出，已经更正。
