### ISSUE TITLE
根节点问题

### ISSUE THREAD

**Issue by serazhu** [wangdoc/javascript-tutorial#20]
阮老师，在读‘’Document 节点‘’这一章节中，看到文章开始有说document是文档的根节点，文章下面又说document.documentElement返回的文档的根节点。到底哪个正确呢。看MDN说document.documentElement返回的文档的根元素。可w3c的文档上又说获取根节点的两种方式中有document.documentElement。这些要怎么理解呢。

**Comment by ruanyf** [comment]
谢谢指出，我写得不严谨，已经改了。

Document 节点代表整个文档。document.documentElement 代表文档的根元素节点。
