### ISSUE TITLE
修正笔误

### ISSUE THREAD

**Issue by allen05ren** [wangdoc/javascript-tutorial#201]
此处的 `IDBOpenDBRequest` 应为 `IDBRequest` 吧

https://github.com/wangdoc/javascript-tutorial/blob/master/docs/bom/indexeddb.md#L381

此处的 `该反复返回` 应为 `该方法返回`
https://github.com/wangdoc/javascript-tutorial/blame/master/docs/elements/video.md#L69

此处的 `当前视频回访` 应为 `当前视频回放`
https://github.com/wangdoc/javascript-tutorial/blame/master/docs/elements/video.md#L104

此处的 `音量变回` 应为 `音量变化`
https://github.com/wangdoc/javascript-tutorial/blame/master/docs/elements/video.md#L149

**Comment by ruanyf** [comment]
`IDBOpenDBRequest`继承了`IDBRequest`接口。

其他都改掉了，谢谢指出。
