### ISSUE TITLE
新对象等价问题

### ISSUE THREAD

**Issue by nutbrain** [wangdoc/javascript-tutorial#202]
阮老师您好，我发现js教程->面向对象编程->Object对象的相关方法->3.Object.create()中的代码段：obj1,obj2,obj3中，obj1和其他的两个是否有细微差别？obj1的原型对象是{}，{}的原型对象是Object.prototype. 而obj2和obj3的原型对象都是Object.prototype.原型链的长度不一样，这里是否不等价？

**Comment by ruanyf** [comment]
是的，确实有细微差别。不过，这里就不考虑这点差别了，因为对实际应用的影响不是很大。
