### ISSUE TITLE
修正两处小笔误

### ISSUE THREAD

**Issue by allen05ren** [wangdoc/javascript-tutorial#203]
严格来说，这两处不算笔误。
1. 构建函数 -> 构造函数

> `instanceof`运算符的左边是实例对象，右边是构造函数。它会检查右边构建函数的原型对象（prototype），是否在左边对象的原型链上。因此，下面两种写法是等价的。

https://github.com/wangdoc/javascript-tutorial/blame/master/docs/oop/prototype.md#L265

2. 此处演示代码最后一行的 Object.create(null) -> obj，后文描述里用的 obj（因此`instanceof`就认为`obj`不是`Object`的实例。）

```javascript
var obj = Object.create(null);
typeof obj // "object"
Object.create(null) instanceof Object // false
```

https://github.com/wangdoc/javascript-tutorial/blame/master/docs/oop/prototype.md#L301

**Comment by ruanyf** [comment]
谢谢指出，已经改正。

**Comment by allen05ren** [comment]
@ruanyf 

```javascript
v instanceof Vehicle
// 等同于
Vehicle.prototype.isPrototypeOf(v)
```

上面代码中，`Object`是对象的构造函数，它的原型对象是`Object.prototype`，`isPrototypeOf()`方法用于检查某个对象是否为另一个对象的原型，详细解释见后文。

这个地方似乎改错了，Object 和 Object.prototype 似乎应当改成 Vehicle 和 Vehicle.prototype

**Comment by ruanyf** [comment]
谢谢指出，已经改正。
