### ISSUE TITLE
“闭包是可以读取其他函数内部变量的函数”。感觉不是那么准确

### ISSUE THREAD

**Issue by chenzhiwei0109** [wangdoc/javascript-tutorial#204]
阮老师您好，如果是全局作用域下的一个函数，读取到全局下的变量，根据MDN的解释应该算是闭包的一种吧？而之所以从函数A内部返回出一个函数B,有变量指向B后一直保存，是因为一直有外部引用着这个函数，造成他和他的词法环境一直被占用不被释放，这只是闭包的一种用法，本质还是作用域机制+垃圾回收。感觉这样表述不太准确哦~
https://wangdoc.com/javascript/types/function.html#%E9%97%AD%E5%8C%85

**Comment by ruanyf** [comment]
谢谢提醒，已经加上了补充说明。
