### ISSUE TITLE
小错误，单引号全角符

### ISSUE THREAD

**Issue by iuuKai** [wangdoc/javascript-tutorial#206]
https://wangdoc.com/javascript/bom/arraybuffer.html#%E8%AF%BB%E5%8F%96%E6%96%87%E4%BB%B6

就在该 《2.6 读取文件》demo代码处（‘file'）

错误：`<input type=’file' onchange='readfile(this.files[0])'></input>`
修正：`<input type='file' onchange='readfile(this.files[0])'></input>`

**Comment by iuuKai** [comment]
> https://wangdoc.com/javascript/bom/arraybuffer.html#%E8%AF%BB%E5%8F%96%E6%96%87%E4%BB%B6
> 
> 就在该 《2.6 读取文件》demo代码处（‘file'）
> 
> 错误：<input type=’file' onchange='readfile(this.files[0])'>
> 修正：<input type='file' onchange='readfile(this.files[0])'>

**Comment by iuuKai** [comment]
> https://wangdoc.com/javascript/bom/arraybuffer.html#%E8%AF%BB%E5%8F%96%E6%96%87%E4%BB%B6
> 
> 就在该 《2.6 读取文件》demo代码处（‘file'）
> 
> 错误：`<input type=’file' onchange='readfile(this.files[0])'>`
> 修正：`<input type='file' onchange='readfile(this.files[0])'>`

**Comment by ruanyf** [comment]
谢谢指出，已经改正。
