### ISSUE TITLE
关于翻译成少数民族语言

### ISSUE THREAD

**Issue by SilvaQ** [wangdoc/javascript-tutorial#208]
老师你好(@ruanyf)，
    我想和身边兄弟一起把这些精彩极致的创作翻译成少数民族语言的内容，分享给更多母语非中文的同胞们的学习。
目前已确定的目标是翻译成 维吾尔语(新疆维吾尔族语言)。后面如果条件允许的话翻译成哈萨克族，柯尔克孜族等语种。

1. 不知道对这事儿老师有何看法或建议？
2. 我们能否得到授权进行这种本地化传播？对此老师有没有什么要求或者需要我们注意的点？
3. 翻译出的内容能否直接贡献给这个项目，这个项目提供多语言？还是最好我们单独建立仓库来管理和展现？

**Comment by ruanyf** [comment]
欢迎翻译，完全没有问题。提一下“出自网道项目”，就可以了。

翻译版本先放在你们自己的仓库。
