### ISSUE TITLE
Object 对象的相关方法hasOwnProperty

### ISSUE THREAD

**Issue by wenxudong090161** [wangdoc/javascript-tutorial#209]
老师您好，这一节提到

> 对象实例的hasOwnProperty方法返回一个布尔值，用于判断某个属性定义在对象自身，还是定义在原型链上。

单独用hasOwnProperty应该只能判断是否定义在对象自身，无法判断是否定义在原型链上的

**Comment by ruanyf** [comment]
不在自身，又不在原型链上，还能在哪里？
