### ISSUE TITLE
严格模式启用方法（2）单个函数

### ISSUE THREAD

**Issue by wenxudong090161** [wangdoc/javascript-tutorial#210]
老师您好，文中提到

> 有时，需要把不同的脚本合并在一个文件里面。如果一个脚本是严格模式，另一个脚本不是，它们的合并就可能出错。严格模式的脚本在前，则合并后的脚本都是严格模式；如果正常模式的脚本在前，则合并后的脚本都是正常模式。这两种情况下，合并后的结果都是不正确的。这时可以考虑把整个脚本文件放在一个立即执行的匿名函数之中。
> 
> (function () {
>   'use strict';
>   // some code here
> })();

这里把整个脚本文件放在一个立即执行的严格模式匿名函数之中，和

> 严格模式的脚本在前，则合并后的脚本都是严格模式

其实是一样的呀，如果说前两种情况下，合并后的结果都是不正确的，那这种合并结果也是不正确的，这种只是保证一定会是严格模式。

**Comment by ruanyf** [comment]
原文指的是合并之前的脚本。
