### ISSUE TITLE
对 XMLHttpRequest.responseType 属性的描述有误

### ISSUE THREAD

**Issue by will-wyx** [wangdoc/javascript-tutorial#211]
本教程中，“浏览器模型->XMLHttpRequest 对象” 章节

其中对 XMLHttpRequest.responseType 属性的描述为 “...这个属性是可写的，可以在调用open()方法之后、调用send()方法之前，设置这个属性的值，**告诉服务器返回指定类型的数据**。...”，而在MDN关于 XMLHttpRequest.responseType 的说明中没有指出该属性值会通知到服务器。

并且通过测试发现，responseType 值并没有包含在请求内容中。个人觉得该属性不是告诉服务器返回什么类型，而是告诉ajax客户端以何种类型处理响应内容。

**Comment by ruanyf** [comment]
谢谢指出，已经改正。
