### ISSUE TITLE
Storage.key()接受一个整数作为参数，返回该位置对应的键名，不是键值

### ISSUE THREAD

**Issue by ChangYanwei** [wangdoc/javascript-tutorial#216]
在浏览器模型章节，对Storage接口的key()方法的介绍中  [Storage.key()](https://wangdoc.com/javascript/bom/storage.html#storagekey)   ，有这样一段描述：

> Storage.key()接受一个整数作为参数（从零开始），返回该位置对应的键值。

它返回的是该位置对应的键名，不是键值。

**Comment by ruanyf** [comment]
谢谢指出，已经更正。
