### ISSUE TITLE
关于按位取整的性能表述的疑问

### ISSUE THREAD

**Issue by mzvast** [wangdoc/javascript-tutorial#219]
位置： #218
此处我测下来是或更快。

拿文中的例子改了改做了个测试，代码如下
```js
console.time('否否');
for (let i = 0; i < 10000; i++) {
    ~~2.9; // 2
    ~~47.11; // 47
    ~~1.9999; // 1
    ~~3; // 3
}

console.timeEnd('否否');

console.time('或0');
for (let i = 0; i < 10000; i++) {
    2.9 | 0; // 2
    47.11 | 0; // 47
    1.9999 | 0; // 1
    3 | 0; // 3
}

console.timeEnd('或0');
```

打印结果
- node下v12.16.1
![image](https://user-images.githubusercontent.com/8097465/117559957-35ed0c80-b0bc-11eb-8648-859ea84a7719.png)

- chrome 90.0.4430.93 (Official Build) (x86_64)
 ![image](https://user-images.githubusercontent.com/8097465/117559961-41d8ce80-b0bc-11eb-932e-346900093330.png)

## 问题跟踪路径
[无意间翻到一篇掘金](https://juejin.cn/post/6953777965838630926)
[局部困惑](https://stackoverflow.com/questions/22277172/how-does-work-as-math-floor)
[顺藤摸瓜找到本文](https://wangdoc.com/javascript/operators/bit.html)（否否操作次数 多的怎么会快呢）
写测试发现问题，issue&PR

**Comment by mzvast** [comment]
@ruanyf 请问close的原因是？

**Comment by ruanyf** [comment]
表达混乱且随意，看不出价值。

**Comment by mzvast** [comment]
> 表达混乱且随意，看不出价值。

表述是欠妥，捋了一下。建议可配置一个ISSUE 模版。

这问题的价值是对于性能的论断。
