### ISSUE TITLE
属性描述对象一节针对configurable的描述似乎有误

### ISSUE THREAD

**Issue by jacty** [wangdoc/javascript-tutorial#226]
![image](https://user-images.githubusercontent.com/4190959/125530487-551796fc-2082-4147-9ebf-99ffe71c0456.png)
根据规格描述，当 configurable 为 false 时，value 是可以修改的，而 writable 是只可修改成 false。所以，咱们 configurable 一节开篇说 value 和 writable 不可修改似乎有歧义，即便后文有强调。但个人认为开篇把不可修改当成了常规行为，后文的强调当成了例外行为，似乎与规格的意义不一致。
![image](https://user-images.githubusercontent.com/4190959/125531300-9dae0f5d-4f2b-4918-83fa-b5729f9453bc.png)
然后第一个例子中的 value 不可修改是因为 writable 为 false,而不是因为 configurable 为 false，所以例子后的描述应当也是有歧义的。感觉这个小节的行文不是很易于理解，configurable 本质上是无法决定 value 是否可以成功修改的，只有 writable 才可以决定。
烦请老师确认下我此处理解是否有误。多谢。
原文链接：https://wangdoc.com/javascript/stdlib/attributes.html#configurable

**Comment by ruanyf** [comment]
谢谢指出，已经改得更清晰一些。
