### ISSUE TITLE
关于函数参数的传递方式的异议

### ISSUE THREAD

**Issue by cjmace1** [wangdoc/javascript-tutorial#227]
![image](https://user-images.githubusercontent.com/30013028/125721669-769b84ce-8239-4b73-b323-eaf2b9092eb1.png)
[图片链接原文地址](https://wangdoc.com/javascript/types/function.html)
[《Javascript 高级程序设计》第三版中有这么一句话 ECMAScript中所有函数的参数都是按值传递的](https://zhuanlan.zhihu.com/p/336035216)
这一部分内容可能需要再考据一下。
函数的参数都是值传递，只是变量类型有值类型和引用类型之分。

**Comment by ruanyf** [comment]
同一件事，说法不同。
