### ISSUE TITLE
请问文档中关于Array对象的reduce方法部分描述是不是有误

### ISSUE THREAD

**Issue by ylc6223** [wangdoc/javascript-tutorial#228]
各位大大,我在阅读文档的时候跟着练习发现了一个问题
在标准库数组对象Array这一章中关于reduce方法的介绍:
文档中如下定义
reduce方法和reduceRight方法的第一个参数都是一个函数。该函数接受以下四个参数。
累积变量，默认为数组的第一个成员
当前变量，默认为数组的第二个成员
当前位置（从0开始）    //经查询,打印发现index是从1开始,reduce方法的参数函数遍历数组每一个成员的时候,index不等于该数组成员的下标,只有指定了初始值的时候,index才从0开始,否则为1
原数组

//而MDN中关于当前位置索引是如此介绍的:
reduce(function callbackFn(accumulator, currentValue, index, array) { ... }, initialValue)
index 可选
数组中正在处理的当前元素的索引。 如果提供了initialValue，则起始索引号为0，否则从索引1起始。
initialValue可选
作为第一次调用 callback函数时的第一个参数的值。 如果没有提供初始值，则将使用数组中的第一个元素。 

如果确实存在描述不准确的地方,还请及时更新相应文档谢谢

**Comment by ruanyf** [comment]
谢谢指出，已经更正。
