### ISSUE TITLE
”运算符“章节里的多次提到的”运算子“术语是不是用错了？

### ISSUE THREAD

**Issue by only1zhuo** [wangdoc/javascript-tutorial#229]
文中”运算符“章节里多次提到的”运算子“应该是指“操作数”，如下加法运算符”章节里的一句话：
>  如果一个运算子是字符串，另一个运算子是非字符串，这时非字符串会转成字符串，再连接在一起。

但是，在 [MDN 繁体版本的“表达式与运算符”介绍](https://developer.mozilla.org/zh-TW/docs/orphaned/Web/JavaScript/Guide/Expressions_and_Operators) 里，明显“运算子”是指“运算符”，“运算元”才是“操作数”。 

如下图：
![image](https://user-images.githubusercontent.com/26796048/126730590-59fcd02c-078c-4532-9a64-52ce2c139418.png)

这里是不是弄错了？

另外，在 [MDN 简体版本的“表达式与运算符”介绍](https://developer.mozilla.org/zh-CN/docs/orphaned/Web/JavaScript/Guide/Expressions_and_Operators) 里，均用“运算符”和“操作数”来描述“表达式”，是否应该统一下说法，使用简体版本说法，一律改为“运算符”和“操作数”术语？

如下图：
![image](https://user-images.githubusercontent.com/26796048/126730560-d7c36cc4-394f-4078-bc2f-fabcfe558933.png)

**Comment by ruanyf** [comment]
我习惯把 Operand 称为“运算子”。如果有混淆，以后改成“操作数”吧。
