### ISSUE TITLE
还是更喜欢旧版的那个页面样式

### ISSUE THREAD

**Issue by JunwuHuang** [wangdoc/javascript-tutorial#23]
旧版的  http://javascript.ruanyifeng.com/introduction/intro.html
然后好像访问的时候，速度不如以前了。是因为最近服务器被攻击的原因吗？

**Comment by ruanyf** [comment]
后面只做 Wangdoc 了，样式慢慢调整。至少在手机端，是比旧版好很多。

旧版的访问速度下降，应该是上了CDN的原因了。
