### ISSUE TITLE
addEventListener第三个参数的讲解不全，参考一下MDN的可好

### ISSUE THREAD

**Issue by Kun8018** [wangdoc/javascript-tutorial#231]
addEventListener第三个参数的讲解不全，应该不只是捕获阶段，还有别的参数，passive等

**Comment by ruanyf** [comment]
谢谢指出，已经补上。

https://github.com/wangdoc/javascript-tutorial/commit/5d7484cdadfe9a7e47d0ff579d8bed5eda30f170
