### ISSUE TITLE
参考链接：更新 or 删除

### ISSUE THREAD

**Issue by tianheg** [wangdoc/javascript-tutorial#238]
types/function 文件的第二个参考链接：
```
- Mark Daggett, [Functions Explained](http://markdaggett.com/blog/2013/02/15/functions-explained/)
```
链接已经失效，并且在网站中没有找到这篇文章。

我在 Wayback Machine 中找到了 [归档](https://web.archive.org/web/20160911170816/http://markdaggett.com/blog/2013/02/15/functions-explained)。可是，国人如果没有能力无法访问。

我的问题是，这条参考链接是更新为Wayback Machine中的链接，还是直接删除。

---
我正在逐一检查每一部分的参考链接，修复失效的链接。遇到这个问题，不知道如何选择。

**Comment by ruanyf** [comment]
我来改一下链接。https://github.com/wangdoc/javascript-tutorial/commit/f901426d946ba4ced8f3b0ff70bc73d01e27c382
