### ISSUE TITLE
请教一个关于 左移位运算 的问题

### ISSUE THREAD

**Issue by qs-cosmos** [wangdoc/javascript-tutorial#24]
<img width="943" alt="2018-08-03 8 21 36" src="https://user-images.githubusercontent.com/33800508/43643670-9f5a6516-975e-11e8-9ad5-fb0703ce1b3a.png">

![2018-08-03 8 21 20](https://user-images.githubusercontent.com/33800508/43643708-cd87082c-975e-11e8-8676-24ae895b0e48.png)

我认为第二张图的结果表明，左移运算符的最高位即符号位参与了移动，该如何理解呢？
运行环境: Google chrome 版本: 68.0.3440.84

**Comment by ruanyf** [comment]
谢谢指出，已经改正。
