### ISSUE TITLE
峰哥，在 6.3.4 多重继承 这里的专门用了继承链而不是原型链，因为 M2 是不在子类原型链上的只有属性和方法在里面，这里提一下会不会更好

### ISSUE THREAD

**Issue by Jamcy123** [wangdoc/javascript-tutorial#243]
![image](https://user-images.githubusercontent.com/78025185/163700061-b0cd71f7-e416-46e5-bdb1-4961448a6a38.png)
峰哥，在 6.3.4 多重继承 这里的专门用了继承链而不是原型链，因为 M2 是不在子类原型链上的，只有属性和方法在里面，这里提一下这个点会不会更好（一点小建议）

**Comment by ruanyf** [comment]
继承某个对象，就是继承它的属性和方法。

如果这里准备表达，就找不到简洁的说法，觉得有点累赘。表达效果还不如现在。
