### ISSUE TITLE
7.2.1 定时器-setTimeout()，代码执行结果与教程不一致

### ISSUE THREAD

**Issue by kevinlys88** [wangdoc/javascript-tutorial#244]
书上期望结果是1，但实际执行结果是 undefined

教程：
<img width="788" alt="截屏2022-04-22 上午6 25 37" src="https://user-images.githubusercontent.com/22601026/164561836-00e6c496-10d0-4ff0-8a96-d4be2006bb19.png">

vscode debug: 
![截屏2022-04-22 上午6 25 03](https://user-images.githubusercontent.com/22601026/164561858-4b73c916-7422-4781-98e9-2ab22528d728.png)

**Comment by ruanyf** [comment]
原文没错。
