### ISSUE TITLE
2.3 数值 一章 中 5.2 parseFloat 一节 的错误

### ISSUE THREAD

**Issue by yuu2lee4** [wangdoc/javascript-tutorial#246]
该节中有以下描述错误：
如果参数不是字符串，或者字符串的第一个字符不能转化为浮点数，则返回NaN

这里应该行为跟parseInt一样，参数不是字符串，会先隐式转换为字符串，所以parseFloat([123]) 不会返回NaN

**Comment by ruanyf** [comment]
谢谢提交，已经合并了。
