### ISSUE TITLE
变量名错误

### ISSUE THREAD

**Issue by JERRY-Z-J-R** [wangdoc/javascript-tutorial#253]
[javascript-tutorial](https://github.com/wangdoc/javascript-tutorial)/[docs](https://github.com/wangdoc/javascript-tutorial/tree/master/docs)/[basic](https://github.com/wangdoc/javascript-tutorial/tree/master/docs/basic)/grammar.md

`While`语句包括一个循环条件和一段代码块，只要条件为真，就不断循环执行代码块。

while的首字母应该小写。

**Comment by ruanyf** [comment]
谢谢指出，已经更正。
