### ISSUE TITLE
这是我看不懂的

### ISSUE THREAD

**Issue by linjialiang** [wangdoc/javascript-tutorial#264]
> 这是我看不懂的

![图片](https://github.com/wangdoc/javascript-tutorial/assets/8848263/7e4022db-ff8b-4735-b6ae-c0e2fca5afbf)

**Comment by linjialiang** [comment]
![图片](https://github.com/wangdoc/javascript-tutorial/assets/8848263/accfa3d4-dbe0-48d3-9815-f831a2f9582f)

**Comment by ruanyf** [comment]
此处不答疑。

**Comment by heshuyi** [comment]
输出hello是因为b的隐式调用，undefined是因为函数的直接使用导致

**Comment by ChaoKing2020** [comment]
> 输出hello是因为b的隐式调用，undefined是因为函数的直接使用导致

为什么会出现undefined还是不太明白
