### ISSUE TITLE
示例代码中存在笔误

### ISSUE THREAD

**Issue by chrisjiang0330** [wangdoc/javascript-tutorial#276]
JavaScript教程 -> 2.数据类型 -> 2.7数组 -> 3.length属性 的第7个示例代码片段中存在笔误，a[2.1]  应修改为 a['p']
![1716779611217](https://github.com/wangdoc/javascript-tutorial/assets/10629101/56b0ad97-862b-4a64-827e-85175bdf0de4)

**Comment by ruanyf** [comment]
原文没错
