### ISSUE TITLE
关于 this 的解释

### ISSUE THREAD

**Issue by bigcake008** [wangdoc/javascript-tutorial#279]
[https://github.com/wangdoc/javascript-tutorial/blob/master/docs/oop/this.md](url)

代码：

> var o = new Object();
> 
> o.f = function () {
>   console.log(this === o);
> }
> 
> var f = function (){
>   o.f.apply(o);
>   // 或者 o.f.call(o);
> };
> 
> // jQuery 的写法
> $('#button').on('click', f);
> 

在函数 _f_ 中调用 _o.f.apply(o)_ 使得 _this_ 获得正确指向，其中 _apply_ 并不是必要的，也就是说可以直接调用 _o.f()_ 即可获得正确指向。其原因是在函数 _f_ 中调用实例 _o_ 的方法 _f_ ，其上下文已经指向实例 _o_ 。

**Comment by ruanyf** [comment]
谢谢指出，已经改正。
