### ISSUE TITLE
关于“数组”章节

### ISSUE THREAD

**Issue by Ynjxsjmh** [wangdoc/javascript-tutorial#28]
此[章节](https://wangdoc.com/javascript/types/array.html)下面的`数组的空位` 这一小节中，如下图片处，我怎么觉得是 `数组空位影响了length属性`
![default](https://user-images.githubusercontent.com/40143136/44144833-a69beece-a0bb-11e8-8d26-a18c5c32b093.png)

![default](https://user-images.githubusercontent.com/40143136/44144939-1aee9182-a0bc-11e8-961c-52d2de2d9812.png)

**Comment by ruanyf** [comment]
汉语的语义不精确。
