### ISSUE TITLE
Javascript文档内容问题 && Javascript document comment issues

### ISSUE THREAD

**Issue by Wstyld** [wangdoc/javascript-tutorial#280]
<img width="1022" alt="截屏2024-08-03 11 59 59" src="https://github.com/user-attachments/assets/46b69c12-6519-493b-b2d5-107e4b9141e7">
for循环的两种情况都一样，第二个应该是自减。
The two cases of the for-loop are the same, and the second should be self-subtracting.

**Comment by shibor** [comment]
我应经收到你的邮件！

**Comment by ruanyf** [comment]
原文没错
