### ISSUE TITLE
老师，网站样式好像有点问题

### ISSUE THREAD

**Issue by hojas** [wangdoc/javascript-tutorial#281]
<img width="1422" alt="image" src="https://github.com/user-attachments/assets/ffd9e9e0-92ea-48e9-80a1-a71702a1a0d9">

**Comment by ruanyf** [comment]
浏览器可能需要更新了。

**Comment by hojas** [comment]
@ruanyf 用的是最新版 Chrome，当系统是深色模式时会出现这个问题

**Comment by ruanyf** [comment]
已经改好了，你再刷新一下。

**Comment by suzhenghui-sky** [comment]
我还以为只是狐火浏览器才有这个问题，以为该网站不适配火狐，没想到其他人也有这种问题，到现在还是这样。
![图片](https://github.com/user-attachments/assets/9e3b0dcc-6137-422c-9d09-6da6c3d3a19e)

**Comment by ruanyf** [comment]
@suzhenghui-sky 上次只更新了 JS 教程，没更新 ES6 教程，现在好了。
