### ISSUE TITLE
示例代码存在遗漏

### ISSUE THREAD

**Issue by theDrunkFish** [wangdoc/javascript-tutorial#289]
JavaScript 教程 -> 6.面向对象编程 -> 6.5 严格模式 -> 3.1 只读属性不可写
[JavaScript教程 -> 3.1 只读属性不可写](https://wangdoc.com/javascript/oop/strict#%E5%8F%AA%E8%AF%BB%E5%B1%9E%E6%80%A7%E4%B8%8D%E5%8F%AF%E5%86%99)

![example](https://github.com/user-attachments/assets/c0c03120-aad3-4cfc-9e2e-cf158151f8e5)

**Comment by ruanyf** [comment]
谢谢指出，已经更正。
