### ISSUE TITLE
函数声明问题

### ISSUE THREAD

**Issue by wangzongxu** [wangdoc/javascript-tutorial#4]
在您的章节函数部分拷来的两段代码，有些不理解。

```js
if (false) {
  function f() {}
}
f() // 不报错
```

1. 为什么在chrome中运行是报错的？

```js
if (false) {
  var f = function () {};
}
f() // undefined
```

2. 为什么在chrome中运行也是报错的？

- 个人感觉两个例子中，由于变量提升，f被声明了，但是但是未能进入条件语句，所以f值为undefined，调用f会报错。

- 本人js小学生，阮老师忠粉，还请阮老师指教一二。

**Comment by ruanyf** [comment]
这是因为 ES6 引入了块级作用域，域名只在声明的作用域里面有效。

原文是针对 ES5 写的。这一段已经过时了，我把它删掉。
