### ISSUE TITLE
文本小错误

### ISSUE THREAD

**Issue by shen076** [wangdoc/javascript-tutorial#42]
- https://wangdoc.com/javascript/types/number.html#%E6%95%B0%E5%80%BC%E8%8C%83%E5%9B%B4
-1075 次方还是能展示的。和 -1074 次方结果一样
```javascript
Math.pow(2, -1076) // 0  
```

**Comment by ruanyf** [comment]
Chrome 浏览器 Math.pow(2, -1075) 返回 0。

**Comment by shen076** [comment]
嗯，我疏忽了。
今天用mac chrome试了一下是Math.pow(2, -1075) 返回 0
但是 windows chrome 64位，69版本 Math.pow(2, -1075) 返回不同
