### ISSUE TITLE
关于运算符会返回布尔值的问题

### ISSUE THREAD

**Issue by leyeee** [wangdoc/javascript-tutorial#45]
在 数据类型中的布尔值 章节中，有一段是下面这样的：
> 下列运算符会返回布尔值：
> 两元逻辑运算符： && (And)，|| (Or)
> 前置逻辑运算符： ! (Not)
> 相等运算符：===，!==，==，!=
> 比较运算符：>，>=，<，<=

我在MDN上看到的是 `&&`运算符 和 `||` 运算符实际上返回一个指定操作数的值，这里是否表达有歧义？

**Comment by ruanyf** [comment]
谢谢指出，已经删掉了这一行。
