### ISSUE TITLE
1.2 数值精度部分不正确

### ISSUE THREAD

**Issue by PaulineZhou** [wangdoc/javascript-tutorial#47]
[https://wangdoc.com/javascript/types/number.html#%E6%95%B0%E5%80%BC%E7%B2%BE%E5%BA%A6](https://wangdoc.com/javascript/types/number.html#%E6%95%B0%E5%80%BC%E7%B2%BE%E5%BA%A6)

其中写道

> 第1位：符号位，0表示正数，1表示负数
> 第2位到第12位（共11位）：指数部分
> 第13位到第64位（共52位）：小数部分（即有效数字）

下面又写道

> (-1)^符号位 * 1.xx...xx * 2^指数部分

这两个部分不对应啊，哪个是第二部分哪个是第三部分，请阮老师明示

**Comment by PaulineZhou** [comment]
接着下面的部分继续写道

> 指数部分一共有11个二进制位，因此大小范围就是0到2047。IEEE 754 规定，如果指数部分的值在0到2047之间（不含两个端点），那么有效数字的第一位默认总是1，不保存在64位浮点数之中。

11个二进制位的大小应该为0到4095 ，即11位全都为1的话，就是2的12次方减1等于4096-1等于4095

阮老师……

**Comment by ruanyf** [comment]
从左往右递增。

**Comment by PaulineZhou** [comment]
理解了，我以为下面的地方是码位说明，原来是数值计算方式
