### ISSUE TITLE
Location对象/URL 的编码和解码 中有格式错误

### ISSUE THREAD

**Issue by magical-l** [wangdoc/javascript-tutorial#52]
https://wangdoc.com/javascript/bom/location.html#url-%E7%9A%84%E7%BC%96%E7%A0%81%E5%92%8C%E8%A7%A3%E7%A0%81
1，“逗号”后圆括号里用的是单引号。
2，下文中写的是“单引号”，但后面括号中是反引号`，并且出现了格式错误。但不敢确定作者本意想写单引号还是反引号，故没提pull request，提个issue。

**Comment by ruanyf** [comment]
谢谢指出，已经改正。
