### ISSUE TITLE
deploy.sh执行

### ISSUE THREAD

**Issue by Mongolia2016** [wangdoc/javascript-tutorial#56]
我在git bash中执行./deploy.sh，得到结果为iv undefined，请问deploy.sh后面有什么参数需要设置呢，我想把您的工程运行起来，作为一个网站方便查询，谢谢！

**Comment by ruanyf** [comment]
安装 loppo，然后在项目根目录下运行`loppo`命令即可。https://www.npmjs.com/package/loppo
