### ISSUE TITLE
Node 接口中 NodeValue描述错误

### ISSUE THREAD

**Issue by myweico** [wangdoc/javascript-tutorial#62]
[出错地址](https://wangdoc.com/javascript/dom/node.html#nodeprototypenodevalue)

错误位置：
/***********
只有文本节点（text）和注释节点（comment）有文本值，因此这两类节点的nodeValue可以返回结果，其他类型的节点一律返回null。同样的，也只有这两类节点可以设置nodeValue属性的值，其他类型的节点设置无效。
*************/

**阮老师，属性节点的nodeValue经测试可以返回结果并且可以设置。**

[测试地址](http://jsfiddle.net/weimy/xwhnvqaL/1/)

**Comment by ruanyf** [comment]
谢谢指出，已经更正。
