### ISSUE TITLE
代码书写错误

### ISSUE THREAD

**Issue by renchenhao** [wangdoc/javascript-tutorial#67]
`(function($, window, document) {

  function go(num) {
  }

  function handleEvents() {
  }

  function initialize() {
  }

  function dieCarouselDie() {
  }

  //attach to the global scope
  window.finalCarousel = {
    init : initialize,
    destroy : dieCouraselDie
  }

})( jQuery, window, document );`
问题：
  function dieCarouselDie() {
  }与destroy : dieCouraselDie 函数名与destroy属性值，不一致 ！

**Comment by ruanyf** [comment]
谢谢指出，已经改正。
