### ISSUE TITLE
文档描述错误

### ISSUE THREAD

**Issue by new9xgh** [wangdoc/javascript-tutorial#73]
附录：网页元素接口 => img => 第9点 事件属性
地址：https://wangdoc.com/javascript/elements/image.html#事件属性

描述错误：“图像加载完成，会触发onerror属性指定的回调函数。”
应该是：“图片加载过中发生错误，会触发onerror属性指定的回调函数。”

**Comment by ruanyf** [comment]
谢谢指出，已经更正。
