### ISSUE TITLE
文档描述小问题

### ISSUE THREAD

**Issue by new9xgh** [wangdoc/javascript-tutorial#74]
附录：网页元素接口 => form  => htmlformelement-的实例属性
地址：https://wangdoc.com/javascript/elements/form.html#htmlformelement-的实例属性

文本：acceptCharset：字符串，表示服务器所能接受的字符编码，多个编码格式之间或空格分隔。

"多个编码格式之间或空格分隔" 中间漏了 "**使用逗号**"。
大概是："多个编码格式之间**使用逗号**或空格分隔"

**Comment by ruanyf** [comment]
谢谢指出，已经更正。
