### ISSUE TITLE
JavaScript 教程 /事件/ 其他常见事件/剪贴板事件 

### ISSUE THREAD

**Issue by fanbingkun** [wangdoc/javascript-tutorial#81]
这三个事件都是ClipboardEvent接口的实例。ClipboardEvent有一个实例属性clipboardData，是一个 DataTransfer 对象，存放剪贴的数据。具体的 API 接口和操作方法，请参见《触摸事件》的 DataTransfer 对象部分。

好像不是在《触摸事件》  而是在拖拉事件

**Comment by fanbingkun** [comment]
顺便问下老师怎么获取剪切的内容呢

**Comment by fanbingkun** [comment]
顺便问下老师，
document.addEventListener('copy', function (e) {
  console.log(e)
});
这个事件对象里面有可以获取到复制的内容吗？

**Comment by ruanyf** [comment]
事件对象拿不到内容，这个要用 Clipboard API。https://developer.mozilla.org/en-US/docs/Web/API/Clipboard

**Comment by ruanyf** [comment]
已经改成《拖拉事件》了。
