### ISSUE TITLE
History 对象章节书写有误

### ISSUE THREAD

**Issue by qiaodaima** [wangdoc/javascript-tutorial#82]
阮前辈您好，在阅读` History 对象` 章节时，
我调出控制台试验 `History 对象` 的一些属性和方法，

然后按照文中的写法，发现代码不能正常运行，
诸如
```
History.length
History.back();
...
```

后面得知，`History` 应该写成 ` history` 😯

**Comment by ruanyf** [comment]
window.history 属性指向 History 对象。前者是后者的访问方式，访问 History 对象的接口。
